///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddGroupMemberRequestModel {
  int? groupId;
  int? memberId;

  AddGroupMemberRequestModel({
    this.groupId,
    this.memberId,
  });
  AddGroupMemberRequestModel.fromJson(Map<String, dynamic> json) {
    groupId = json['group_id']?.toInt();
    memberId = json['member_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['group_id'] = groupId;
    data['member_id'] = memberId;
    return data;
  }
}
