///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommonGroupsResponseModel {
  String? message;
  String? error;

  CommonGroupsResponseModel({
    this.message,
    this.error,
  });
  CommonGroupsResponseModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    error = json['error']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['error'] = error;
    return data;
  }
}
