///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateGroupsResponseModel {
  int? groupId;
  String? message;

  CreateGroupsResponseModel({
    this.groupId,
    this.message,
  });
  CreateGroupsResponseModel.fromJson(Map<String, dynamic> json) {
    groupId = json['group_id']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['group_id'] = groupId;
    data['message'] = message;
    return data;
  }
}
