///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetGroupsDetailsModelGroupDetailsMembers {
/*
{
  "email": "pmeet007m@gmail.com",
  "gender": "male",
  "member_id": 1,
  "mobile": 1212121212,
  "user_name": "Test User"
}
*/

  String? email;
  String? gender;
  int? memberId;
  int? mobile;
  String? userName;

  GetGroupsDetailsModelGroupDetailsMembers({
    this.email,
    this.gender,
    this.memberId,
    this.mobile,
    this.userName,
  });
  GetGroupsDetailsModelGroupDetailsMembers.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    memberId = json['member_id']?.toInt();
    mobile = json['mobile']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['gender'] = gender;
    data['member_id'] = memberId;
    data['mobile'] = mobile;
    data['user_name'] = userName;
    return data;
  }
}

class GetGroupsDetailsModelGroupDetails {
/*
{
  "created_at": "Wed, 04 Sep 2024 05:23:45 GMT",
  "email": "pmeet007m@gmail.com",
  "group_id": 2,
  "group_name": "Collge Friends",
  "members": [
    {
      "email": "pmeet007m@gmail.com",
      "gender": "male",
      "member_id": 1,
      "mobile": 1212121212,
      "user_name": "Test User"
    }
  ],
  "mobile": 1212121212,
  "user_id": 1,
  "user_name": "Test User"
}
*/

  String? createdAt;
  String? email;
  int? groupId;
  String? groupName;
  List<GetGroupsDetailsModelGroupDetailsMembers?>? members;
  int? mobile;
  int? userId;
  String? userName;

  GetGroupsDetailsModelGroupDetails({
    this.createdAt,
    this.email,
    this.groupId,
    this.groupName,
    this.members,
    this.mobile,
    this.userId,
    this.userName,
  });
  GetGroupsDetailsModelGroupDetails.fromJson(Map<String, dynamic> json) {
    createdAt = json['created_at']?.toString();
    email = json['email']?.toString();
    groupId = json['group_id']?.toInt();
    groupName = json['group_name']?.toString();
    if (json['members'] != null) {
      final v = json['members'];
      final arr0 = <GetGroupsDetailsModelGroupDetailsMembers>[];
      v.forEach((v) {
        arr0.add(GetGroupsDetailsModelGroupDetailsMembers.fromJson(v));
      });
      members = arr0;
    }
    mobile = json['mobile']?.toInt();
    userId = json['user_id']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['created_at'] = createdAt;
    data['email'] = email;
    data['group_id'] = groupId;
    data['group_name'] = groupName;
    if (members != null) {
      final v = members;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['members'] = arr0;
    }
    data['mobile'] = mobile;
    data['user_id'] = userId;
    data['user_name'] = userName;
    return data;
  }
}

class GetGroupsDetailsModel {
/*
{
  "group_details": {
    "created_at": "Wed, 04 Sep 2024 05:23:45 GMT",
    "email": "pmeet007m@gmail.com",
    "group_id": 2,
    "group_name": "Collge Friends",
    "members": [
      {
        "email": "pmeet007m@gmail.com",
        "gender": "male",
        "member_id": 1,
        "mobile": 1212121212,
        "user_name": "Test User"
      }
    ],
    "mobile": 1212121212,
    "user_id": 1,
    "user_name": "Test User"
  }
}
*/

  GetGroupsDetailsModelGroupDetails? groupDetails;

  GetGroupsDetailsModel({
    this.groupDetails,
  });
  GetGroupsDetailsModel.fromJson(Map<String, dynamic> json) {
    groupDetails = (json['group_details'] != null) ? GetGroupsDetailsModelGroupDetails.fromJson(json['group_details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (groupDetails != null) {
      data['group_details'] = groupDetails!.toJson();
    }
    return data;
  }
}
