///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterRequestModel {
  String? userName;
  String? email;
  String? mobile;
  String? password;
  int? securityPin;
  String? gender;
  String? birthDate;

  RegisterRequestModel({
    this.userName,
    this.email,
    this.mobile,
    this.password,
    this.securityPin,
    this.gender,
    this.birthDate,
  });
  RegisterRequestModel.fromJson(Map<String, dynamic> json) {
    userName = json['user_name']?.toString();
    email = json['email']?.toString();
    mobile = json['mobile']?.toString();
    password = json['password']?.toString();
    securityPin = json['security_pin']?.toInt();
    gender = json['gender']?.toString();
    birthDate = json['birth_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_name'] = userName;
    data['email'] = email;
    data['mobile'] = mobile;
    data['password'] = password;
    data['security_pin'] = securityPin;
    data['gender'] = gender;
    data['birth_date'] = birthDate;
    return data;
  }
}
