///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetFriendsByMobileResponseModelFriend {
  String? birthDate;
  String? email;
  String? gender;
  int? mobile;
  int? userId;
  String? userName;

  GetFriendsByMobileResponseModelFriend({
    this.birthDate,
    this.email,
    this.gender,
    this.mobile,
    this.userId,
    this.userName,
  });
  GetFriendsByMobileResponseModelFriend.fromJson(Map<String, dynamic> json) {
    birthDate = json['birth_date']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    mobile = json['mobile']?.toInt();
    userId = json['user_id']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['birth_date'] = birthDate;
    data['email'] = email;
    data['gender'] = gender;
    data['mobile'] = mobile;
    data['user_id'] = userId;
    data['user_name'] = userName;
    return data;
  }
}

class GetFriendsByMobileResponseModel {
  GetFriendsByMobileResponseModelFriend? friend;

  GetFriendsByMobileResponseModel({
    this.friend,
  });
  GetFriendsByMobileResponseModel.fromJson(Map<String, dynamic> json) {
    friend = (json['friend'] != null) ? GetFriendsByMobileResponseModelFriend.fromJson(json['friend']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (friend != null) {
      data['friend'] = friend!.toJson();
    }
    return data;
  }
}
