///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllFriendsModelFriends {
/*
{
  "birth_date": "Sat, 02 May 1998 00:00:00 GMT",
  "email": "pmeetoo7n@gmail.com",
  "gender": "male",
  "mobile": 1234567890,
  "user_id": 2,
  "user_name": "Test User"
}
*/

  String? birthDate;
  String? email;
  String? gender;
  int? mobile;
  int? userId;
  String? userName;

  GetAllFriendsModelFriends({
    this.birthDate,
    this.email,
    this.gender,
    this.mobile,
    this.userId,
    this.userName,
  });
  GetAllFriendsModelFriends.fromJson(Map<String, dynamic> json) {
    birthDate = json['birth_date']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    mobile = json['mobile']?.toInt();
    userId = json['user_id']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['birth_date'] = birthDate;
    data['email'] = email;
    data['gender'] = gender;
    data['mobile'] = mobile;
    data['user_id'] = userId;
    data['user_name'] = userName;
    return data;
  }
}

class GetAllFriendsModel {
/*
{
  "friends": [
    {
      "birth_date": "Sat, 02 May 1998 00:00:00 GMT",
      "email": "pmeetoo7n@gmail.com",
      "gender": "male",
      "mobile": 1234567890,
      "user_id": 2,
      "user_name": "Test User"
    }
  ]
}
*/

  List<GetAllFriendsModelFriends?>? friends;

  GetAllFriendsModel({
    this.friends,
  });
  GetAllFriendsModel.fromJson(Map<String, dynamic> json) {
    if (json['friends'] != null) {
      final v = json['friends'];
      final arr0 = <GetAllFriendsModelFriends>[];
      v.forEach((v) {
        arr0.add(GetAllFriendsModelFriends.fromJson(v));
      });
      friends = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (friends != null) {
      final v = friends;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['friends'] = arr0;
    }
    return data;
  }
}
