///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NonGroupMemberFriendsModelFriends {
/*
{
  "email": "pmeetoo7n@gmail.com",
  "gender": "male",
  "mobile": 1234567890,
  "user_id": 2,
  "user_name": "Test User"
}
*/

  String? email;
  String? gender;
  int? mobile;
  int? userId;
  String? userName;

  NonGroupMemberFriendsModelFriends({
    this.email,
    this.gender,
    this.mobile,
    this.userId,
    this.userName,
  });
  NonGroupMemberFriendsModelFriends.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    mobile = json['mobile']?.toInt();
    userId = json['user_id']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['gender'] = gender;
    data['mobile'] = mobile;
    data['user_id'] = userId;
    data['user_name'] = userName;
    return data;
  }
}

class NonGroupMemberFriendsModel {
/*
{
  "friends": [
    {
      "email": "pmeetoo7n@gmail.com",
      "gender": "male",
      "mobile": 1234567890,
      "user_id": 2,
      "user_name": "Test User"
    }
  ],
  "message": "success"
}
*/

  List<NonGroupMemberFriendsModelFriends?>? friends;
  String? message;

  NonGroupMemberFriendsModel({
    this.friends,
    this.message,
  });
  NonGroupMemberFriendsModel.fromJson(Map<String, dynamic> json) {
    if (json['friends'] != null) {
      final v = json['friends'];
      final arr0 = <NonGroupMemberFriendsModelFriends>[];
      v.forEach((v) {
        arr0.add(NonGroupMemberFriendsModelFriends.fromJson(v));
      });
      friends = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (friends != null) {
      final v = friends;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['friends'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
