///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginResponseModelUser {
/*
{
  "birth_date": "male",
  "email": "pmeet007m@gmail.com",
  "gender": "male",
  "mobile": 638657556,
  "user_id": 1,
  "user_name": "Test User"
}
*/

  String? birthDate;
  String? email;
  String? gender;
  int? mobile;
  int? userId;
  String? userName;

  LoginResponseModelUser({
    this.birthDate,
    this.email,
    this.gender,
    this.mobile,
    this.userId,
    this.userName,
  });
  LoginResponseModelUser.fromJson(Map<String, dynamic> json) {
    birthDate = json['birth_date']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    mobile = json['mobile']?.toInt();
    userId = json['user_id']?.toInt();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['birth_date'] = birthDate;
    data['email'] = email;
    data['gender'] = gender;
    data['mobile'] = mobile;
    data['user_id'] = userId;
    data['user_name'] = userName;
    return data;
  }
}

class LoginResponseModel {
/*
{
  "statusCode": 200,
  "message": "dsds",
  "error": "Invalid mobile number",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNTM5MTY4NywianRpIjoiNjJkNjdhNGYtZDQ5MS00YTJjLThmMTctZmM4NDYzODA5NzYzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzI1MzkxNjg3LCJjc3JmIjoiZjc0MWExMmItM2U5Yi00YzYwLTg1NTYtMGI5MjJkY2I5ZmFiIiwiZXhwIjoxNzI1MzkyNTg3fQ.W6ZQVpT7amjM_wJktxkECmtdg3RJyH9xF3zVD0irkc4",
  "user": {
    "birth_date": "male",
    "email": "pmeet007m@gmail.com",
    "gender": "male",
    "mobile": 638657556,
    "user_id": 1,
    "user_name": "Test User"
  }
}
*/

  int? statusCode;
  String? message;
  String? error;
  String? token;
  LoginResponseModelUser? user;

  LoginResponseModel({
    this.statusCode,
    this.message,
    this.error,
    this.token,
    this.user,
  });
  LoginResponseModel.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    error = json['error']?.toString();
    token = json['token']?.toString();
    user = (json['user'] != null) ? LoginResponseModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    data['error'] = error;
    data['token'] = token;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
