///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OTPVerificationResponseModel {
  String? message;
  String? error;
  int? statusCode;

  OTPVerificationResponseModel({
    this.message,
    this.error,
    this.statusCode,
  });
  OTPVerificationResponseModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    error = json['error']?.toString();
    statusCode = json['statusCode']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['error'] = error;
    data['statusCode'] = statusCode;
    return data;
  }
}
