///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddBudgetResponseModel {
/*
{
  "message": "dsds",
  "error": "Invalid mobile number"
}
*/

  String? message;
  String? error;

  AddBudgetResponseModel({
    this.message,
    this.error,
  });
  AddBudgetResponseModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    error = json['error']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['error'] = error;
    return data;
  }
}
