///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCurrentMonthTotalAmountModel {
/*
{
  "total_amount": "200.00"
}
*/

  String? totalAmount;

  GetCurrentMonthTotalAmountModel({
    this.totalAmount,
  });
  GetCurrentMonthTotalAmountModel.fromJson(Map<String, dynamic> json) {
    totalAmount = json['total_amount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_amount'] = totalAmount;
    return data;
  }
}
