///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetHomeTransactionsModelDataTransactions {
/*
{
  "amount": "50.00",
  "created_at": "05:20",
  "description": "Shared dinner",
  "is_paid": 1,
  "payment_id": 1,
  "split_id": 1,
  "user_id": 1
}
*/

  String? amount;
  String? createdAt;
  String? description;
  int? isPaid;
  int? paymentId;
  int? splitId;
  int? userId;

  GetHomeTransactionsModelDataTransactions({
    this.amount,
    this.createdAt,
    this.description,
    this.isPaid,
    this.paymentId,
    this.splitId,
    this.userId,
  });
  GetHomeTransactionsModelDataTransactions.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    createdAt = json['created_at']?.toString();
    description = json['description']?.toString();
    isPaid = json['is_paid']?.toInt();
    paymentId = json['payment_id']?.toInt();
    splitId = json['split_id']?.toInt();
    userId = json['user_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['created_at'] = createdAt;
    data['description'] = description;
    data['is_paid'] = isPaid;
    data['payment_id'] = paymentId;
    data['split_id'] = splitId;
    data['user_id'] = userId;
    return data;
  }
}

class GetHomeTransactionsModelData {
/*
{
  "amount": "200.00",
  "date": "2024-09-04",
  "transactions": [
    {
      "amount": "50.00",
      "created_at": "05:20",
      "description": "Shared dinner",
      "is_paid": 1,
      "payment_id": 1,
      "split_id": 1,
      "user_id": 1
    }
  ]
}
*/

  String? amount;
  String? date;
  List<GetHomeTransactionsModelDataTransactions?>? transactions;

  GetHomeTransactionsModelData({
    this.amount,
    this.date,
    this.transactions,
  });
  GetHomeTransactionsModelData.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    date = json['date']?.toString();
    if (json['transactions'] != null) {
      final v = json['transactions'];
      final arr0 = <GetHomeTransactionsModelDataTransactions>[];
      v.forEach((v) {
        arr0.add(GetHomeTransactionsModelDataTransactions.fromJson(v));
      });
      transactions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['date'] = date;
    if (transactions != null) {
      final v = transactions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['transactions'] = arr0;
    }
    return data;
  }
}

class GetHomeTransactionsModel {
/*
{
  "data": [
    {
      "amount": "200.00",
      "date": "2024-09-04",
      "transactions": [
        {
          "amount": "50.00",
          "created_at": "05:20",
          "description": "Shared dinner",
          "is_paid": 1,
          "payment_id": 1,
          "split_id": 1,
          "user_id": 1
        }
      ]
    }
  ],
  "message": "Succcess"
}
*/

  List<GetHomeTransactionsModelData?>? data;
  String? message;

  GetHomeTransactionsModel({
    this.data,
    this.message,
  });
  GetHomeTransactionsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetHomeTransactionsModelData>[];
      v.forEach((v) {
        arr0.add(GetHomeTransactionsModelData.fromJson(v));
      });
      data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
