///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCurrencyRateModelConversionRates {
  double? GBP;
  double? AED;
  double? AFN;
  double? ALL;
  double? AMD;
  double? ANG;
  double? AOA;
  double? ARS;
  double? AUD;
  double? AWG;
  double? AZN;
  double? BAM;
  double? BBD;
  double? BDT;
  double? BGN;
  double? BHD;
  double? BIF;
  double? BMD;
  double? BND;
  double? BOB;
  double? BRL;
  double? BSD;
  double? BTN;
  double? BWP;
  double? BYN;
  double? BZD;
  double? CAD;
  double? CDF;
  double? CHF;
  double? CLP;
  double? CNY;
  double? COP;
  double? CRC;
  double? CUP;
  double? CVE;
  double? CZK;
  double? DJF;
  double? DKK;
  double? DOP;
  double? DZD;
  double? EGP;
  double? ERN;
  double? ETB;
  double? EUR;
  double? FJD;
  double? FKP;
  double? FOK;
  double? GEL;
  double? GGP;
  double? GHS;
  double? GIP;
  double? GMD;
  double? GNF;
  double? GTQ;
  double? GYD;
  double? HKD;
  double? HNL;
  double? HRK;
  double? HTG;
  double? HUF;
  double? IDR;
  double? ILS;
  double? IMP;
  double? INR;
  double? IQD;
  double? IRR;
  double? ISK;
  double? JEP;
  double? JMD;
  double? JOD;
  double? JPY;
  double? KES;
  double? KGS;
  double? KHR;
  double? KID;
  double? KMF;
  double? KRW;
  double? KWD;
  double? KYD;
  double? KZT;
  double? LAK;
  double? LBP;
  double? LKR;
  double? LRD;
  double? LSL;
  double? LYD;
  double? MAD;
  double? MDL;
  double? MGA;
  double? MKD;
  double? MMK;
  double? MNT;
  double? MOP;
  double? MRU;
  double? MUR;
  double? MVR;
  double? MWK;
  double? MXN;
  double? MYR;
  double? MZN;
  double? NAD;
  double? NGN;
  double? NIO;
  double? NOK;
  double? NPR;
  double? NZD;
  double? OMR;
  double? PAB;
  double? PEN;
  double? PGK;
  double? PHP;
  double? PKR;
  double? PLN;
  double? PYG;
  double? QAR;
  double? RON;
  double? RSD;
  double? RUB;
  double? RWF;
  double? SAR;
  double? SBD;
  double? SCR;
  double? SDG;
  double? SEK;
  double? SGD;
  double? SHP;
  double? SLE;
  double? SLL;
  double? SOS;
  double? SRD;
  double? SSP;
  double? STN;
  double? SYP;
  double? SZL;
  double? THB;
  double? TJS;
  double? TMT;
  double? TND;
  double? TOP;
  double? TRY;
  double? TTD;
  double? TVD;
  double? TWD;
  double? TZS;
  double? UAH;
  double? UGX;
  double? USD;
  double? UYU;
  double? UZS;
  double? VES;
  double? VND;
  double? VUV;
  double? WST;
  double? XAF;
  double? XCD;
  double? XDR;
  double? XOF;
  double? XPF;
  double? YER;
  double? ZAR;
  double? ZMW;
  double? ZWL;

  GetCurrencyRateModelConversionRates({
    this.GBP,
    this.AED,
    this.AFN,
    this.ALL,
    this.AMD,
    this.ANG,
    this.AOA,
    this.ARS,
    this.AUD,
    this.AWG,
    this.AZN,
    this.BAM,
    this.BBD,
    this.BDT,
    this.BGN,
    this.BHD,
    this.BIF,
    this.BMD,
    this.BND,
    this.BOB,
    this.BRL,
    this.BSD,
    this.BTN,
    this.BWP,
    this.BYN,
    this.BZD,
    this.CAD,
    this.CDF,
    this.CHF,
    this.CLP,
    this.CNY,
    this.COP,
    this.CRC,
    this.CUP,
    this.CVE,
    this.CZK,
    this.DJF,
    this.DKK,
    this.DOP,
    this.DZD,
    this.EGP,
    this.ERN,
    this.ETB,
    this.EUR,
    this.FJD,
    this.FKP,
    this.FOK,
    this.GEL,
    this.GGP,
    this.GHS,
    this.GIP,
    this.GMD,
    this.GNF,
    this.GTQ,
    this.GYD,
    this.HKD,
    this.HNL,
    this.HRK,
    this.HTG,
    this.HUF,
    this.IDR,
    this.ILS,
    this.IMP,
    this.INR,
    this.IQD,
    this.IRR,
    this.ISK,
    this.JEP,
    this.JMD,
    this.JOD,
    this.JPY,
    this.KES,
    this.KGS,
    this.KHR,
    this.KID,
    this.KMF,
    this.KRW,
    this.KWD,
    this.KYD,
    this.KZT,
    this.LAK,
    this.LBP,
    this.LKR,
    this.LRD,
    this.LSL,
    this.LYD,
    this.MAD,
    this.MDL,
    this.MGA,
    this.MKD,
    this.MMK,
    this.MNT,
    this.MOP,
    this.MRU,
    this.MUR,
    this.MVR,
    this.MWK,
    this.MXN,
    this.MYR,
    this.MZN,
    this.NAD,
    this.NGN,
    this.NIO,
    this.NOK,
    this.NPR,
    this.NZD,
    this.OMR,
    this.PAB,
    this.PEN,
    this.PGK,
    this.PHP,
    this.PKR,
    this.PLN,
    this.PYG,
    this.QAR,
    this.RON,
    this.RSD,
    this.RUB,
    this.RWF,
    this.SAR,
    this.SBD,
    this.SCR,
    this.SDG,
    this.SEK,
    this.SGD,
    this.SHP,
    this.SLE,
    this.SLL,
    this.SOS,
    this.SRD,
    this.SSP,
    this.STN,
    this.SYP,
    this.SZL,
    this.THB,
    this.TJS,
    this.TMT,
    this.TND,
    this.TOP,
    this.TRY,
    this.TTD,
    this.TVD,
    this.TWD,
    this.TZS,
    this.UAH,
    this.UGX,
    this.USD,
    this.UYU,
    this.UZS,
    this.VES,
    this.VND,
    this.VUV,
    this.WST,
    this.XAF,
    this.XCD,
    this.XDR,
    this.XOF,
    this.XPF,
    this.YER,
    this.ZAR,
    this.ZMW,
    this.ZWL,
  });
  GetCurrencyRateModelConversionRates.fromJson(Map<String, dynamic> json) {
    GBP = json['GBP']?.toDouble();
    AED = json['AED']?.toDouble();
    AFN = json['AFN']?.toDouble();
    ALL = json['ALL']?.toDouble();
    AMD = json['AMD']?.toDouble();
    ANG = json['ANG']?.toDouble();
    AOA = json['AOA']?.toDouble();
    ARS = json['ARS']?.toDouble();
    AUD = json['AUD']?.toDouble();
    AWG = json['AWG']?.toDouble();
    AZN = json['AZN']?.toDouble();
    BAM = json['BAM']?.toDouble();
    BBD = json['BBD']?.toDouble();
    BDT = json['BDT']?.toDouble();
    BGN = json['BGN']?.toDouble();
    BHD = json['BHD']?.toDouble();
    BIF = json['BIF']?.toDouble();
    BMD = json['BMD']?.toDouble();
    BND = json['BND']?.toDouble();
    BOB = json['BOB']?.toDouble();
    BRL = json['BRL']?.toDouble();
    BSD = json['BSD']?.toDouble();
    BTN = json['BTN']?.toDouble();
    BWP = json['BWP']?.toDouble();
    BYN = json['BYN']?.toDouble();
    BZD = json['BZD']?.toDouble();
    CAD = json['CAD']?.toDouble();
    CDF = json['CDF']?.toDouble();
    CHF = json['CHF']?.toDouble();
    CLP = json['CLP']?.toDouble();
    CNY = json['CNY']?.toDouble();
    COP = json['COP']?.toDouble();
    CRC = json['CRC']?.toDouble();
    CUP = json['CUP']?.toDouble();
    CVE = json['CVE']?.toDouble();
    CZK = json['CZK']?.toDouble();
    DJF = json['DJF']?.toDouble();
    DKK = json['DKK']?.toDouble();
    DOP = json['DOP']?.toDouble();
    DZD = json['DZD']?.toDouble();
    EGP = json['EGP']?.toDouble();
    ERN = json['ERN']?.toDouble();
    ETB = json['ETB']?.toDouble();
    EUR = json['EUR']?.toDouble();
    FJD = json['FJD']?.toDouble();
    FKP = json['FKP']?.toDouble();
    FOK = json['FOK']?.toDouble();
    GEL = json['GEL']?.toDouble();
    GGP = json['GGP']?.toDouble();
    GHS = json['GHS']?.toDouble();
    GIP = json['GIP']?.toDouble();
    GMD = json['GMD']?.toDouble();
    GNF = json['GNF']?.toDouble();
    GTQ = json['GTQ']?.toDouble();
    GYD = json['GYD']?.toDouble();
    HKD = json['HKD']?.toDouble();
    HNL = json['HNL']?.toDouble();
    HRK = json['HRK']?.toDouble();
    HTG = json['HTG']?.toDouble();
    HUF = json['HUF']?.toDouble();
    IDR = json['IDR']?.toDouble();
    ILS = json['ILS']?.toDouble();
    IMP = json['IMP']?.toDouble();
    INR = json['INR']?.toDouble();
    IQD = json['IQD']?.toDouble();
    IRR = json['IRR']?.toDouble();
    ISK = json['ISK']?.toDouble();
    JEP = json['JEP']?.toDouble();
    JMD = json['JMD']?.toDouble();
    JOD = json['JOD']?.toDouble();
    JPY = json['JPY']?.toDouble();
    KES = json['KES']?.toDouble();
    KGS = json['KGS']?.toDouble();
    KHR = json['KHR']?.toDouble();
    KID = json['KID']?.toDouble();
    KMF = json['KMF']?.toDouble();
    KRW = json['KRW']?.toDouble();
    KWD = json['KWD']?.toDouble();
    KYD = json['KYD']?.toDouble();
    KZT = json['KZT']?.toDouble();
    LAK = json['LAK']?.toDouble();
    LBP = json['LBP']?.toDouble();
    LKR = json['LKR']?.toDouble();
    LRD = json['LRD']?.toDouble();
    LSL = json['LSL']?.toDouble();
    LYD = json['LYD']?.toDouble();
    MAD = json['MAD']?.toDouble();
    MDL = json['MDL']?.toDouble();
    MGA = json['MGA']?.toDouble();
    MKD = json['MKD']?.toDouble();
    MMK = json['MMK']?.toDouble();
    MNT = json['MNT']?.toDouble();
    MOP = json['MOP']?.toDouble();
    MRU = json['MRU']?.toDouble();
    MUR = json['MUR']?.toDouble();
    MVR = json['MVR']?.toDouble();
    MWK = json['MWK']?.toDouble();
    MXN = json['MXN']?.toDouble();
    MYR = json['MYR']?.toDouble();
    MZN = json['MZN']?.toDouble();
    NAD = json['NAD']?.toDouble();
    NGN = json['NGN']?.toDouble();
    NIO = json['NIO']?.toDouble();
    NOK = json['NOK']?.toDouble();
    NPR = json['NPR']?.toDouble();
    NZD = json['NZD']?.toDouble();
    OMR = json['OMR']?.toDouble();
    PAB = json['PAB']?.toDouble();
    PEN = json['PEN']?.toDouble();
    PGK = json['PGK']?.toDouble();
    PHP = json['PHP']?.toDouble();
    PKR = json['PKR']?.toDouble();
    PLN = json['PLN']?.toDouble();
    PYG = json['PYG']?.toDouble();
    QAR = json['QAR']?.toDouble();
    RON = json['RON']?.toDouble();
    RSD = json['RSD']?.toDouble();
    RUB = json['RUB']?.toDouble();
    RWF = json['RWF']?.toDouble();
    SAR = json['SAR']?.toDouble();
    SBD = json['SBD']?.toDouble();
    SCR = json['SCR']?.toDouble();
    SDG = json['SDG']?.toDouble();
    SEK = json['SEK']?.toDouble();
    SGD = json['SGD']?.toDouble();
    SHP = json['SHP']?.toDouble();
    SLE = json['SLE']?.toDouble();
    SLL = json['SLL']?.toDouble();
    SOS = json['SOS']?.toDouble();
    SRD = json['SRD']?.toDouble();
    SSP = json['SSP']?.toDouble();
    STN = json['STN']?.toDouble();
    SYP = json['SYP']?.toDouble();
    SZL = json['SZL']?.toDouble();
    THB = json['THB']?.toDouble();
    TJS = json['TJS']?.toDouble();
    TMT = json['TMT']?.toDouble();
    TND = json['TND']?.toDouble();
    TOP = json['TOP']?.toDouble();
    TRY = json['TRY']?.toDouble();
    TTD = json['TTD']?.toDouble();
    TVD = json['TVD']?.toDouble();
    TWD = json['TWD']?.toDouble();
    TZS = json['TZS']?.toDouble();
    UAH = json['UAH']?.toDouble();
    UGX = json['UGX']?.toDouble();
    USD = json['USD']?.toDouble();
    UYU = json['UYU']?.toDouble();
    UZS = json['UZS']?.toDouble();
    VES = json['VES']?.toDouble();
    VND = json['VND']?.toDouble();
    VUV = json['VUV']?.toDouble();
    WST = json['WST']?.toDouble();
    XAF = json['XAF']?.toDouble();
    XCD = json['XCD']?.toDouble();
    XDR = json['XDR']?.toDouble();
    XOF = json['XOF']?.toDouble();
    XPF = json['XPF']?.toDouble();
    YER = json['YER']?.toDouble();
    ZAR = json['ZAR']?.toDouble();
    ZMW = json['ZMW']?.toDouble();
    ZWL = json['ZWL']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['GBP'] = GBP;
    data['AED'] = AED;
    data['AFN'] = AFN;
    data['ALL'] = ALL;
    data['AMD'] = AMD;
    data['ANG'] = ANG;
    data['AOA'] = AOA;
    data['ARS'] = ARS;
    data['AUD'] = AUD;
    data['AWG'] = AWG;
    data['AZN'] = AZN;
    data['BAM'] = BAM;
    data['BBD'] = BBD;
    data['BDT'] = BDT;
    data['BGN'] = BGN;
    data['BHD'] = BHD;
    data['BIF'] = BIF;
    data['BMD'] = BMD;
    data['BND'] = BND;
    data['BOB'] = BOB;
    data['BRL'] = BRL;
    data['BSD'] = BSD;
    data['BTN'] = BTN;
    data['BWP'] = BWP;
    data['BYN'] = BYN;
    data['BZD'] = BZD;
    data['CAD'] = CAD;
    data['CDF'] = CDF;
    data['CHF'] = CHF;
    data['CLP'] = CLP;
    data['CNY'] = CNY;
    data['COP'] = COP;
    data['CRC'] = CRC;
    data['CUP'] = CUP;
    data['CVE'] = CVE;
    data['CZK'] = CZK;
    data['DJF'] = DJF;
    data['DKK'] = DKK;
    data['DOP'] = DOP;
    data['DZD'] = DZD;
    data['EGP'] = EGP;
    data['ERN'] = ERN;
    data['ETB'] = ETB;
    data['EUR'] = EUR;
    data['FJD'] = FJD;
    data['FKP'] = FKP;
    data['FOK'] = FOK;
    data['GEL'] = GEL;
    data['GGP'] = GGP;
    data['GHS'] = GHS;
    data['GIP'] = GIP;
    data['GMD'] = GMD;
    data['GNF'] = GNF;
    data['GTQ'] = GTQ;
    data['GYD'] = GYD;
    data['HKD'] = HKD;
    data['HNL'] = HNL;
    data['HRK'] = HRK;
    data['HTG'] = HTG;
    data['HUF'] = HUF;
    data['IDR'] = IDR;
    data['ILS'] = ILS;
    data['IMP'] = IMP;
    data['INR'] = INR;
    data['IQD'] = IQD;
    data['IRR'] = IRR;
    data['ISK'] = ISK;
    data['JEP'] = JEP;
    data['JMD'] = JMD;
    data['JOD'] = JOD;
    data['JPY'] = JPY;
    data['KES'] = KES;
    data['KGS'] = KGS;
    data['KHR'] = KHR;
    data['KID'] = KID;
    data['KMF'] = KMF;
    data['KRW'] = KRW;
    data['KWD'] = KWD;
    data['KYD'] = KYD;
    data['KZT'] = KZT;
    data['LAK'] = LAK;
    data['LBP'] = LBP;
    data['LKR'] = LKR;
    data['LRD'] = LRD;
    data['LSL'] = LSL;
    data['LYD'] = LYD;
    data['MAD'] = MAD;
    data['MDL'] = MDL;
    data['MGA'] = MGA;
    data['MKD'] = MKD;
    data['MMK'] = MMK;
    data['MNT'] = MNT;
    data['MOP'] = MOP;
    data['MRU'] = MRU;
    data['MUR'] = MUR;
    data['MVR'] = MVR;
    data['MWK'] = MWK;
    data['MXN'] = MXN;
    data['MYR'] = MYR;
    data['MZN'] = MZN;
    data['NAD'] = NAD;
    data['NGN'] = NGN;
    data['NIO'] = NIO;
    data['NOK'] = NOK;
    data['NPR'] = NPR;
    data['NZD'] = NZD;
    data['OMR'] = OMR;
    data['PAB'] = PAB;
    data['PEN'] = PEN;
    data['PGK'] = PGK;
    data['PHP'] = PHP;
    data['PKR'] = PKR;
    data['PLN'] = PLN;
    data['PYG'] = PYG;
    data['QAR'] = QAR;
    data['RON'] = RON;
    data['RSD'] = RSD;
    data['RUB'] = RUB;
    data['RWF'] = RWF;
    data['SAR'] = SAR;
    data['SBD'] = SBD;
    data['SCR'] = SCR;
    data['SDG'] = SDG;
    data['SEK'] = SEK;
    data['SGD'] = SGD;
    data['SHP'] = SHP;
    data['SLE'] = SLE;
    data['SLL'] = SLL;
    data['SOS'] = SOS;
    data['SRD'] = SRD;
    data['SSP'] = SSP;
    data['STN'] = STN;
    data['SYP'] = SYP;
    data['SZL'] = SZL;
    data['THB'] = THB;
    data['TJS'] = TJS;
    data['TMT'] = TMT;
    data['TND'] = TND;
    data['TOP'] = TOP;
    data['TRY'] = TRY;
    data['TTD'] = TTD;
    data['TVD'] = TVD;
    data['TWD'] = TWD;
    data['TZS'] = TZS;
    data['UAH'] = UAH;
    data['UGX'] = UGX;
    data['USD'] = USD;
    data['UYU'] = UYU;
    data['UZS'] = UZS;
    data['VES'] = VES;
    data['VND'] = VND;
    data['VUV'] = VUV;
    data['WST'] = WST;
    data['XAF'] = XAF;
    data['XCD'] = XCD;
    data['XDR'] = XDR;
    data['XOF'] = XOF;
    data['XPF'] = XPF;
    data['YER'] = YER;
    data['ZAR'] = ZAR;
    data['ZMW'] = ZMW;
    data['ZWL'] = ZWL;
    return data;
  }
}

class GetCurrencyRateModel {
  String? result;
  String? documentation;
  String? termsOfUse;
  double? timeLastUpdateUnix;
  String? timeLastUpdateUtc;
  double? timeNextUpdateUnix;
  String? timeNextUpdateUtc;
  String? baseCode;
  GetCurrencyRateModelConversionRates? conversionRates;

  GetCurrencyRateModel({
    this.result,
    this.documentation,
    this.termsOfUse,
    this.timeLastUpdateUnix,
    this.timeLastUpdateUtc,
    this.timeNextUpdateUnix,
    this.timeNextUpdateUtc,
    this.baseCode,
    this.conversionRates,
  });
  GetCurrencyRateModel.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    documentation = json['documentation']?.toString();
    termsOfUse = json['terms_of_use']?.toString();
    // timeLastUpdateUnix = json['time_last_update_unix']?.toDouble();
    // timeLastUpdateUtc = json['time_last_update_utc']?.toString();
    // timeNextUpdateUnix = json['time_next_update_unix']?.toDouble();
    // timeNextUpdateUtc = json['time_next_update_utc']?.toString();
    // baseCode = json['base_code']?.toString();
    conversionRates = (json['conversion_rates'] != null) ? GetCurrencyRateModelConversionRates.fromJson(json['conversion_rates']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['documentation'] = documentation;
    data['terms_of_use'] = termsOfUse;
    data['time_last_update_unix'] = timeLastUpdateUnix;
    data['time_last_update_utc'] = timeLastUpdateUtc;
    data['time_next_update_unix'] = timeNextUpdateUnix;
    data['time_next_update_utc'] = timeNextUpdateUtc;
    data['base_code'] = baseCode;
    if (conversionRates != null) {
      data['conversion_rates'] = conversionRates!.toJson();
    }
    return data;
  }
}
