///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaymentUploadReceiptResponseModel {
  String? amount;

  PaymentUploadReceiptResponseModel({
    this.amount,
  });
  PaymentUploadReceiptResponseModel.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    return data;
  }
}
